// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using brainfreeze_new.Server.Models;

#nullable disable

namespace brainfreeze_new.Server.Migrations
{
    [DbContext(typeof(ScoreboardDBContext))]
    [Migration("20250519153643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("brainfreeze_new.Server.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Complete 10 Simon games",
                            Name = "Simoneer",
                            TargetValue = 10,
                            Type = "SimonGamesCompleted",
                            UnlockCondition = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "Complete 10 Simon games",
                            Name = "Simoneer",
                            TargetValue = 10,
                            Type = "SimonGamesCompleted",
                            UnlockCondition = ""
                        },
                        new
                        {
                            Id = 3,
                            Description = "Complete 10 Simon games",
                            Name = "Simoneer",
                            TargetValue = 10,
                            Type = "SimonGamesCompleted",
                            UnlockCondition = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "Complete 10 Simon games",
                            Name = "Simoneer",
                            TargetValue = 10,
                            Type = "SimonGamesCompleted",
                            UnlockCondition = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "Complete 10 Simon games",
                            Name = "Simoneer",
                            TargetValue = 10,
                            Type = "SimonGamesCompleted",
                            UnlockCondition = ""
                        },
                        new
                        {
                            Id = 6,
                            Description = "Complete 10 Simon games",
                            Name = "Simoneer",
                            TargetValue = 10,
                            Type = "SimonGamesCompleted",
                            UnlockCondition = ""
                        },
                        new
                        {
                            Id = 7,
                            Description = "Complete 10 Simon games",
                            Name = "Simoneer",
                            TargetValue = 10,
                            Type = "SimonGamesCompleted",
                            UnlockCondition = ""
                        },
                        new
                        {
                            Id = 8,
                            Description = "Win 2 multiplayer matches",
                            Name = "Multiplayer Pro",
                            TargetValue = 2,
                            Type = "MultiplayerWins",
                            UnlockCondition = "Win 2 multiplayer matches to unlock"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Win 2 multiplayer matches",
                            Name = "Multiplayer Pro",
                            TargetValue = 2,
                            Type = "MultiplayerWins",
                            UnlockCondition = "Win 2 multiplayer matches to unlock"
                        });
                });

            modelBuilder.Entity("brainfreeze_new.Server.Models.GameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("brainfreeze_new.Server.Models.Scoreboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardflipScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NrgScore")
                        .HasColumnType("integer");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("SimonScore")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Scoreboards");
                });

            modelBuilder.Entity("brainfreeze_new.Server.Models.UserAchievement", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("brainfreeze_new.Server.Models.UserAchievement", b =>
                {
                    b.HasOne("brainfreeze_new.Server.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });
#pragma warning restore 612, 618
        }
    }
}
